<a href="https://colab.research.google.com/github/praykar/codesimple/blob/main/03_Numpy_2_Cont_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome to Numpy-2-Cont")

Welcome to Numpy-2-Cont


## Agenda

- **Usecase: calculate NPS**✅
    - loading data: `np.loadtxt()`✅
    - `np.empty()`✅
    - `np.unique()`✅


- **Introduction to use case**✅

    
- **2-D arrays (Matrices)**✅
    - `reshape()`
    - 2 Questions✅
    - Transpose✅
    - Converting Matrix back to Vector - `flatten()`✅

- **Indexing and Slicing on 2D** ✅
    - Indexing✅

    - Slicing

    - Masking (Fancy Indexing)




- **Universal Functions (ufunc) on 2D**
    - Aggregate Function/ Reduction functions - `sum()`, `mean()`, `min()`, `max()`
    
    - Axis argument

    - Logical Operations
    
    - Sorting function - `sort()`, `argsort()`

       
       
- **Use Case: Fitness Data analysis**
    - Loading data set and EDA using numpy
    - `np.argmax()`




In [ ]:
import numpy as np

In [ ]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/1_Aug_Beg_Mon/03_Numpy_2_cont/survey.txt
100%|██████████████████████████████████████| 2.55k/2.55k [00:00<00:00, 2.86MB/s]


In [ ]:
score=np.loadtxt("/Users/nikhilsanghi/Downloads/01_dsml-course-main-live/batches/1_Aug_Beg_Mon/02_Numpy_2/survey.txt",dtype='int')

In [ ]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
type(None)

NoneType

In [ ]:
arr=np.empty(shape=score.shape,dtype="<U20")
arr

array(['', '', '', ..., '', '', ''], dtype='<U20')

In [ ]:
# np.array(["scaler","academy","dsml"],dtype="<U5")

In [ ]:
# np.array(["scaler","academy","dsml","dhsujdlhfadskfhdskalfhk"],dtype="U10")

In [ ]:
score<7

array([False, False,  True, ...,  True, False, False])

In [ ]:
score[score<7]

In [ ]:
arr[score<7]="detractors"

In [ ]:
arr

array(['', '', 'detractors', ..., 'detractors', '', ''], dtype='<U20')

In [ ]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
a<3

array([ True,  True, False, False, False])

In [ ]:
b=np.empty(shape=a.shape,dtype="i4")
b


array([  0,   0,   0,   0, 101], dtype=int32)

In [ ]:
a[a<3]=0

In [ ]:
a

array([0, 0, 3, 4, 5])

In [ ]:
b[a<3]=200

In [ ]:
b

array([200, 200,   0,   0, 101], dtype=int32)

In [ ]:
arr[score>8]="promotors"

In [ ]:
arr[(score==7) | (score==8)]="passives"

In [ ]:
arr

array(['passives', 'promotors', 'detractors', ..., 'detractors',
       'promotors', 'promotors'], dtype='<U20')

In [ ]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [ ]:
a=score[:10]

In [ ]:
a

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9])

In [ ]:
b=np.empty(shape=a.shape,dtype="U20")
b

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U20')

In [ ]:
a>7

array([False,  True, False,  True,  True, False, False,  True,  True,
        True])

In [ ]:
b[a<7]="detractors"

In [ ]:
b


array(['', '', 'detractors', '', '', 'detractors', '', '', '', ''],
      dtype='<U20')

In [ ]:
a

array([ 7, 10,  5,  9,  9,  4,  7,  9,  9,  9])

In [ ]:
b[a>8]="promotors"

In [ ]:
b

array(['', 'promotors', 'detractors', 'promotors', 'promotors',
       'detractors', '', 'promotors', 'promotors', 'promotors'],
      dtype='<U20')

In [ ]:
b[(a==7) | (a==8)]="passives"

In [ ]:
b

array(['passives', 'promotors', 'detractors', 'promotors', 'promotors',
       'detractors', 'passives', 'promotors', 'promotors', 'promotors'],
      dtype='<U20')

In [ ]:
arr

array(['passives', 'promotors', 'detractors', ..., 'detractors',
       'promotors', 'promotors'], dtype='<U20')

In [ ]:
np.unique(arr)

array(['detractors', 'passives', 'promotors'], dtype='<U20')

In [ ]:
np.unique(score)

array([ 1,  4,  5,  7,  8,  9, 10])

In [ ]:
result=np.unique(arr,return_counts=True)
result

(array(['detractors', 'passives', 'promotors'], dtype='<U20'),
 array([332, 226, 609]))

In [ ]:
arr.unique()÷

SyntaxError: invalid character '÷' (U+00F7) (2752609629.py, line 1)

In [ ]:
dictionary={}
dictionary[result[0][0]]=result[1][0]
dictionary[result[0][1]]=result[1][1]
dictionary[result[0][2]]=result[1][2]

In [ ]:
result[1][0]

332

In [ ]:
dictionary

{'detractors': 332, 'passives': 226, 'promotors': 609}

In [ ]:
# 2d numpy arrays

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# np.array([[1,2,3],[4,5,6],[7,8,9,10]])


In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 3)

In [ ]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
b.ndim

2

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.size

9

In [ ]:
b.size

6

In [ ]:
c=np.array([1,2,3,4])
c

array([1, 2, 3, 4])

In [ ]:
c.size

4

In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a.size

9

In [ ]:
a.shape


(3, 3)

In [ ]:
a.shape[0]

3

In [ ]:
a.shape[1]

3

In [ ]:
a.shape[0]*a.shape[1]

9

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
b.size

6

In [ ]:
b.shape[0]

2

In [ ]:
b.shape[1]

3

In [ ]:
b.shape[0]*b.shape[1]

6

In [ ]:
d=np.array([[1,2,3,4]])
e=np.array([1,2,3,4])

In [ ]:
d

array([[1, 2, 3, 4]])

In [ ]:
d.ndim

2

In [ ]:
e.ndim

1

In [ ]:
d.shape

(1, 4)

In [ ]:
e.shape


(4,)

In [ ]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.shape

(12,)

In [ ]:
# a.reshape(shape=())

In [ ]:
# a.reshape(x,y...)

In [ ]:
#  a.reshape((x,y...)) # preferrable

In [ ]:
a.reshape((1,12))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
a.reshape((12,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.reshape((2,6))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
a.reshape((6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.reshape((3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.reshape((4,3))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a.reshape((5,4))

ValueError: cannot reshape array of size 12 into shape (5,4)

In [ ]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
# a.reshape((-1,c))
# a.reshape((r,-1))

# a.reshape((-1,-1))

In [ ]:
a.reshape((-1,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
a.reshape((2,-1))

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [ ]:
a.reshape((-1,-1))

ValueError: can only specify one unknown dimension

In [ ]:
a.reshape((-1,5))

ValueError: cannot reshape array of size 12 into shape (5)

In [ ]:
a=a.reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
len(a)

3

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a=np.arange(1,13).reshape((1,12))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
a.T

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
a=a.reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.reshape((12,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a.reshape((1,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
a.reshape((-1,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
a.reshape((a.size,))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1][1] # not recommended in DS

6

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[1,1]

6

In [ ]:
a[2,2]

11

In [ ]:
a[-2,-1]

8

In [ ]:
a[1,-1]

8

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# a[rows,columns]

In [ ]:
a[[0,1,1],[1,2,3]] #recommended

array([2, 7, 8])

In [ ]:
a[(0,1,1),(1,2,3)] # not recommended 

array([2, 7, 8])

In [ ]:
a[[0,1,1],[1,2,3]]

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[[-3,-2,-2],[-3,-2,-1]]

array([2, 7, 8])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a=np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a=a.flatten()
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a=a.reshape((4,3))

In [ ]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
a[[0,1,2],[-2,-1,-1]]

array([2, 6, 9])